-- MySQL Script generated by MySQL Workbench
-- Fri Mar  9 11:21:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema elearningdb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `elearningdb` ;

-- -----------------------------------------------------
-- Schema elearningdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `elearningdb` DEFAULT CHARACTER SET utf8 ;

USE `elearningdb` ;

-- -----------------------------------------------------
-- Table `elearningdb`.`dept`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`dept` (
  `id_dept` INT NOT NULL AUTO_INCREMENT,
  `nom_dept` VARCHAR(14) NOT NULL,
  PRIMARY KEY (`id_dept`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `elearningdb`.`pais`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`pais` (
  `id_pais` INT NOT NULL AUTO_INCREMENT,
  `nom_p` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`id_pais`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `elearningdb`.`tipo_personal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`tipo_personal` (
  `id_tipo` INT NOT NULL AUTO_INCREMENT,
  `nom_tipo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`personal_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`personal_reg` (
  `id_per` INT NOT NULL AUTO_INCREMENT,
  `id_reg` VARCHAR(3) NOT NULL,
  `nom_per` VARCHAR(60) NOT NULL,
  `ape_per` VARCHAR(60) NOT NULL,
  `fecha_creado` DATE NOT NULL,
  `fecha_nac` DATE NOT NULL,
  `obser` VARCHAR(128) NOT NULL,
  `id_dept` INT NOT NULL,
  `id_pais` INT NOT NULL,
  `dir_per` VARCHAR(65) NOT NULL,
  `id_tipo` INT NOT NULL,
  PRIMARY KEY (`id_per`, `id_reg`),
  INDEX `fk_alumno_dept1_idx` (`id_dept` ASC),
  INDEX `fk_alumno_pais1_idx` (`id_pais` ASC),
  INDEX `fk_personal_reg_tipo_personal1_idx` (`id_tipo` ASC),
  CONSTRAINT `fk_alumno_dept1`
    FOREIGN KEY (`id_dept`)
    REFERENCES `elearningdb`.`dept` (`id_dept`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_alumno_pais1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `elearningdb`.`pais` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personal_reg_tipo_personal1`
    FOREIGN KEY (`id_tipo`)
    REFERENCES `elearningdb`.`tipo_personal` (`id_tipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`email_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`email_reg` (
  `id_email` VARCHAR(50) NOT NULL,
  `reg_id_per` INT NOT NULL,
  `reg_id_reg` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_email`, `reg_id_per`, `reg_id_reg`),
  INDEX `fk_email_reg_personal_reg1_idx` (`reg_id_per` ASC, `reg_id_reg` ASC),
  CONSTRAINT `fk_email_reg_personal_reg1`
    FOREIGN KEY (`reg_id_per` , `reg_id_reg`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`telefono` (
  `id_tel` VARCHAR(16) NOT NULL,
  `area_code` VARCHAR(6) NOT NULL,
  `reg_id_per` INT NOT NULL,
  `reg_id_reg` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_tel`, `area_code`, `reg_id_per`, `reg_id_reg`),
  INDEX `fk_telefono_personal_reg1_idx` (`reg_id_per` ASC, `reg_id_reg` ASC),
  CONSTRAINT `fk_telefono_personal_reg1`
    FOREIGN KEY (`reg_id_per` , `reg_id_reg`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`tel_tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`tel_tipo` (
  `id_tp` INT NOT NULL AUTO_INCREMENT,
  `nom_tp` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_tp`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `elearningdb`.`tel_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`tel_reg` (
  `id_tel` VARCHAR(9) NOT NULL,
  `area_code_tel` VARCHAR(3) NOT NULL,
  `asis_id_v` INT NOT NULL,
  `tel_prov_id_prov` INT NOT NULL,
  `tel_tipo_id_tp` INT NOT NULL,
  PRIMARY KEY (`id_tel`, `area_code_tel`, `asis_id_v`, `tel_prov_id_prov`, `tel_tipo_id_tp`),
  INDEX `fk_tel_reg_tel_tipo1_idx` (`tel_tipo_id_tp` ASC),
  CONSTRAINT `fk_tel_reg_tel_tipo1`
    FOREIGN KEY (`tel_tipo_id_tp`)
    REFERENCES `elearningdb`.`tel_tipo` (`id_tp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_spanish_ci;


-- -----------------------------------------------------
-- Table `elearningdb`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`facultad` (
  `id_fac` INT NOT NULL AUTO_INCREMENT,
  `nom_fac` VARCHAR(50) NOT NULL,
  `descrip_fac` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_fac`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`curso` (
  `id_cur` INT NOT NULL AUTO_INCREMENT,
  `facultad_id_fac` INT NOT NULL,
  `nombre_cur` VARCHAR(45) NOT NULL,
  `descrip_cur` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_cur`, `facultad_id_fac`),
  INDEX `fk_curso_facultad1_idx` (`facultad_id_fac` ASC),
  CONSTRAINT `fk_curso_facultad1`
    FOREIGN KEY (`facultad_id_fac`)
    REFERENCES `elearningdb`.`facultad` (`id_fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`inscripcion_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`inscripcion_reg` (
  `id_insc` INT NOT NULL AUTO_INCREMENT,
  `id_fac` INT NOT NULL,
  `reg_id_per` INT NOT NULL,
  `reg_id_reg` VARCHAR(3) NOT NULL,
  `fecha_reg` DATE NOT NULL,
  PRIMARY KEY (`id_insc`, `id_fac`, `reg_id_per`, `reg_id_reg`),
  INDEX `fk_inscripcion_reg_facultad1_idx` (`id_fac` ASC),
  CONSTRAINT `fk_inscripcion_reg_personal_reg1`
    FOREIGN KEY (`reg_id_per` , `reg_id_reg`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscripcion_reg_facultad1`
    FOREIGN KEY (`id_fac`)
    REFERENCES `elearningdb`.`facultad` (`id_fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`asignacion_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`asignacion_reg` (
  `id_doc_asig` INT NOT NULL AUTO_INCREMENT,
  `anio` TINYINT NOT NULL,
  `semestre` TINYINT NOT NULL,
  `inscripcionreg_id_insc` INT NOT NULL,
  `inscripcionreg_id_fac` INT NOT NULL,
  `fecha_creado` DATE NOT NULL,
  PRIMARY KEY (`id_doc_asig`, `anio`, `semestre`, `inscripcionreg_id_insc`, `inscripcionreg_id_fac`),
  INDEX `fk_asignacion_reg_inscripcion_reg1_idx` (`inscripcionreg_id_insc` ASC, `inscripcionreg_id_fac` ASC),
  CONSTRAINT `fk_asignacion_reg_inscripcion_reg1`
    FOREIGN KEY (`inscripcionreg_id_insc` , `inscripcionreg_id_fac`)
    REFERENCES `elearningdb`.`inscripcion_reg` (`id_insc` , `id_fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`catedratico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`catedratico` (
  `id_cat` INT NOT NULL AUTO_INCREMENT,
  `personal_id_per` INT NOT NULL,
  `personal_id_reg` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_cat`, `personal_id_per`, `personal_id_reg`),
  INDEX `fk_catedratico_personal_reg1_idx` (`personal_id_per` ASC, `personal_id_reg` ASC),
  CONSTRAINT `fk_catedratico_personal_reg1`
    FOREIGN KEY (`personal_id_per` , `personal_id_reg`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`ecurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`ecurso` (
  `curso_id_cur` INT NOT NULL,
  `curso_fac_fac` INT NOT NULL,
  `catid_cat` INT NOT NULL,
  PRIMARY KEY (`curso_id_cur`, `curso_fac_fac`, `catid_cat`),
  INDEX `fk_ecurso_curso1_idx` (`curso_id_cur` ASC, `curso_fac_fac` ASC),
  INDEX `fk_ecurso_catedratico1_idx` (`catid_cat` ASC),
  CONSTRAINT `fk_ecurso_curso1`
    FOREIGN KEY (`curso_id_cur` , `curso_fac_fac`)
    REFERENCES `elearningdb`.`curso` (`id_cur` , `facultad_id_fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ecurso_catedratico1`
    FOREIGN KEY (`catid_cat`)
    REFERENCES `elearningdb`.`catedratico` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`evaluacion` (
  `id_ev` INT NOT NULL AUTO_INCREMENT,
  `personal_id_per` INT NOT NULL,
  `personal_id_reg` VARCHAR(3) NOT NULL,
  `ecurso_id_cur` INT NOT NULL,
  `ecurso_fac` INT NOT NULL,
  `ecurso_id_cat` INT NOT NULL,
  `nota_ev` INT NOT NULL,
  `fecha_init` DATE NOT NULL,
  `path_ev` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id_ev`, `personal_id_per`, `personal_id_reg`, `ecurso_id_cur`, `ecurso_fac`, `ecurso_id_cat`),
  INDEX `fk_evaluacion_personal_reg1_idx` (`personal_id_per` ASC, `personal_id_reg` ASC),
  INDEX `fk_evaluacion_ecurso1_idx` (`ecurso_id_cur` ASC, `ecurso_fac` ASC, `ecurso_id_cat` ASC),
  CONSTRAINT `fk_evaluacion_personal_reg1`
    FOREIGN KEY (`personal_id_per` , `personal_id_reg`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_ecurso1`
    FOREIGN KEY (`ecurso_id_cur` , `ecurso_fac` , `ecurso_id_cat`)
    REFERENCES `elearningdb`.`ecurso` (`curso_id_cur` , `curso_fac_fac` , `catid_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`horario` (
  `id_horario` INT NOT NULL AUTO_INCREMENT,
  `curso_id_cur` INT NOT NULL,
  `curso_id_fac` INT NOT NULL,
  PRIMARY KEY (`id_horario`, `curso_id_cur`, `curso_id_fac`),
  INDEX `fk_horario_detalle_curso1_idx` (`curso_id_cur` ASC, `curso_id_fac` ASC),
  CONSTRAINT `fk_horario_detalle_curso1`
    FOREIGN KEY (`curso_id_cur` , `curso_id_fac`)
    REFERENCES `elearningdb`.`curso` (`id_cur` , `facultad_id_fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`asig_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`asig_detalle` (
  `id_doc_asig` INT NOT NULL,
  `id_cur` INT NOT NULL,
  `id_fac` INT NOT NULL,
  `id_horario` INT NOT NULL,
  PRIMARY KEY (`id_doc_asig`, `id_cur`, `id_fac`),
  INDEX `fk_asig_detalle_curso1_idx` (`id_cur` ASC, `id_fac` ASC),
  INDEX `fk_asig_detalle_horario1_idx` (`id_horario` ASC),
  INDEX `fk_asig_detalle_asignacion_reg1_idx` (`id_doc_asig` ASC),
  CONSTRAINT `fk_asig_detalle_curso1`
    FOREIGN KEY (`id_cur` , `id_fac`)
    REFERENCES `elearningdb`.`curso` (`id_cur` , `facultad_id_fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asig_detalle_horario1`
    FOREIGN KEY (`id_horario`)
    REFERENCES `elearningdb`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_asig_detalle_asignacion_reg1`
    FOREIGN KEY (`id_doc_asig`)
    REFERENCES `elearningdb`.`asignacion_reg` (`id_doc_asig`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`nota_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`nota_reg` (
  `id_nota_reg` INT NOT NULL AUTO_INCREMENT,
  `nota_semestre` INT NOT NULL,
  `nota_anio` INT NOT NULL,
  `cur_id_curso` INT NOT NULL,
  `cur_id_fac` INT NOT NULL,
  `cat_id_cat` INT NOT NULL,
  `fecha_in` DATE NOT NULL,
  PRIMARY KEY (`id_nota_reg`, `nota_semestre`, `nota_anio`, `cur_id_curso`, `cur_id_fac`, `cat_id_cat`),
  INDEX `fk_nota_reg_curso1_idx` (`cur_id_curso` ASC, `cur_id_fac` ASC),
  INDEX `fk_nota_reg_catedratico1_idx` (`cat_id_cat` ASC),
  CONSTRAINT `fk_nota_reg_curso1`
    FOREIGN KEY (`cur_id_curso` , `cur_id_fac`)
    REFERENCES `elearningdb`.`curso` (`id_cur` , `facultad_id_fac`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_nota_reg_catedratico1`
    FOREIGN KEY (`cat_id_cat`)
    REFERENCES `elearningdb`.`catedratico` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`docs_reg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`docs_reg` (
  `id_doc` INT NOT NULL,
  `reg_id_per` INT NOT NULL,
  `personal_reg_id` VARCHAR(3) NOT NULL,
  `ecurso_id_cur` INT NOT NULL,
  `ecurso_id_fac` INT NOT NULL,
  `ecurso_id_cat` INT NOT NULL,
  `docs_path` VARCHAR(50) NOT NULL,
  `docs_date_in` DATETIME NOT NULL,
  `docs_nom_tarea` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_doc`, `reg_id_per`, `personal_reg_id`, `ecurso_id_cur`, `ecurso_id_fac`, `ecurso_id_cat`),
  INDEX `fk_docs_reg_personal_reg1_idx` (`reg_id_per` ASC, `personal_reg_id` ASC),
  INDEX `fk_docs_reg_ecurso1_idx` (`ecurso_id_cur` ASC, `ecurso_id_fac` ASC, `ecurso_id_cat` ASC),
  CONSTRAINT `fk_docs_reg_personal_reg1`
    FOREIGN KEY (`reg_id_per` , `personal_reg_id`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_docs_reg_ecurso1`
    FOREIGN KEY (`ecurso_id_cur` , `ecurso_id_fac` , `ecurso_id_cat`)
    REFERENCES `elearningdb`.`ecurso` (`curso_id_cur` , `curso_fac_fac` , `catid_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`cur_material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`cur_material` (
  `id_mat` INT NOT NULL AUTO_INCREMENT,
  `ecurso_id_cur` INT NOT NULL,
  `ecurso_id_fac` INT NOT NULL,
  `ecurso_id_cat` INT NOT NULL,
  `nom_mat` VARCHAR(45) NOT NULL,
  `path_mat` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_mat`, `ecurso_id_cur`, `ecurso_id_fac`, `ecurso_id_cat`),
  INDEX `fk_cur_material_ecurso1_idx` (`ecurso_id_cur` ASC, `ecurso_id_fac` ASC, `ecurso_id_cat` ASC),
  CONSTRAINT `fk_cur_material_ecurso1`
    FOREIGN KEY (`ecurso_id_cur` , `ecurso_id_fac` , `ecurso_id_cat`)
    REFERENCES `elearningdb`.`ecurso` (`curso_id_cur` , `curso_fac_fac` , `catid_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`empleado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`empleado` (
  `id_emp` INT NOT NULL AUTO_INCREMENT,
  `personal_id_per` INT NOT NULL,
  `personal_id_reg` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_emp`, `personal_id_per`, `personal_id_reg`),
  INDEX `fk_empleado_personal_reg1_idx` (`personal_id_per` ASC, `personal_id_reg` ASC),
  CONSTRAINT `fk_empleado_personal_reg1`
    FOREIGN KEY (`personal_id_per` , `personal_id_reg`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`evento` (
  `id_evt` INT NOT NULL,
  `id_emp` INT NOT NULL,
  `fecha_ini` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `nombre_ev` VARCHAR(65) NOT NULL,
  `descrip_ev` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`id_evt`, `id_emp`),
  INDEX `fk_evento_empleado1_idx` (`id_emp` ASC),
  CONSTRAINT `fk_evento_empleado1`
    FOREIGN KEY (`id_emp`)
    REFERENCES `elearningdb`.`empleado` (`id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`noticia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`noticia` (
  `id_noticia` INT NOT NULL,
  `id_emp` INT NOT NULL,
  `nom_noticia` VARCHAR(65) NOT NULL,
  `fecha_creado` DATE NOT NULL,
  `fecha_noticia` DATE NULL,
  PRIMARY KEY (`id_noticia`, `id_emp`),
  INDEX `fk_noticia_empleado1_idx` (`id_emp` ASC),
  CONSTRAINT `fk_noticia_empleado1`
    FOREIGN KEY (`id_emp`)
    REFERENCES `elearningdb`.`empleado` (`id_emp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`foro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`foro` (
  `id_foro` INT NOT NULL AUTO_INCREMENT,
  `id_cat` INT NOT NULL,
  `tema_foro` VARCHAR(65) NOT NULL,
  `fecha_creado` DATETIME NOT NULL,
  `fecha_fin` DATETIME NOT NULL,
  PRIMARY KEY (`id_foro`, `id_cat`),
  INDEX `fk_foro_catedratico1_idx` (`id_cat` ASC),
  CONSTRAINT `fk_foro_catedratico1`
    FOREIGN KEY (`id_cat`)
    REFERENCES `elearningdb`.`catedratico` (`id_cat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`edificio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`edificio` (
  `id_ed` VARCHAR(1) NOT NULL,
  `nom_ed` VARCHAR(16) NOT NULL,
  PRIMARY KEY (`id_ed`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`salon`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`salon` (
  `id_salon` INT NOT NULL AUTO_INCREMENT,
  `edificio_id_ed` VARCHAR(1) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`id_salon`, `edificio_id_ed`),
  INDEX `fk_salon_edificio1_idx` (`edificio_id_ed` ASC),
  CONSTRAINT `fk_salon_edificio1`
    FOREIGN KEY (`edificio_id_ed`)
    REFERENCES `elearningdb`.`edificio` (`id_ed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`horario_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`horario_detalle` (
  `id_horario` INT NOT NULL,
  `edificio_id_ed` VARCHAR(1) NOT NULL,
  `salon_id_salon` INT NOT NULL,
  `horario_dia` VARCHAR(8) NOT NULL,
  `hora_ini` TIME NOT NULL,
  `hora_fin` VARCHAR(45) NOT NULL,
  `seccion` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`id_horario`),
  INDEX `fk_horario_detalle_salon1_idx` (`salon_id_salon` ASC, `edificio_id_ed` ASC),
  CONSTRAINT `fk_horario_detalle_horario1`
    FOREIGN KEY (`id_horario`)
    REFERENCES `elearningdb`.`horario` (`id_horario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_horario_detalle_salon1`
    FOREIGN KEY (`salon_id_salon` , `edificio_id_ed`)
    REFERENCES `elearningdb`.`salon` (`id_salon` , `edificio_id_ed`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`detalle_foro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`detalle_foro` (
  `foro_id_foro` INT NOT NULL,
  `personal_id_per` INT NOT NULL,
  `personal_id_reg` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`foro_id_foro`, `personal_id_per`, `personal_id_reg`),
  INDEX `fk_detalle_alumno_personal_reg1_idx` (`personal_id_per` ASC, `personal_id_reg` ASC),
  CONSTRAINT `fk_detalle_alumno_foro1`
    FOREIGN KEY (`foro_id_foro`)
    REFERENCES `elearningdb`.`foro` (`id_foro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_alumno_personal_reg1`
    FOREIGN KEY (`personal_id_per` , `personal_id_reg`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `elearningdb`.`detalle_nota`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`detalle_nota` (
  `nota_reg_id` INT NOT NULL,
  `per_id_per` INT NOT NULL,
  `per_id_reg` VARCHAR(3) NOT NULL,
  `nota_zona` TINYINT NULL,
  `nota_final` TINYINT NULL,
  PRIMARY KEY (`nota_reg_id`, `per_id_per`, `per_id_reg`),
  INDEX `fk_detalle_nota_personal_reg1_idx` (`per_id_per` ASC, `per_id_reg` ASC),
  CONSTRAINT `fk_detalle_nota_nota_reg1`
    FOREIGN KEY (`nota_reg_id`)
    REFERENCES `elearningdb`.`nota_reg` (`id_nota_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_nota_personal_reg1`
    FOREIGN KEY (`per_id_per` , `per_id_reg`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `seguridad` ;

-- -----------------------------------------------------
-- Table `seguridad`.`aplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`aplicacion` (
  `id_aplicacion` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_aplicacion` VARCHAR(50) NOT NULL,
  `descripcion_aplicacion` VARCHAR(80) NOT NULL,
  `habilitar_aplicacion` TINYINT(1) NOT NULL,
  `id_reporte` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_aplicacion`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seguridad`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`usuario` (
  `id_usuario` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `nombre_usuario` VARCHAR(50) NOT NULL,
  `apellido_usuario` VARCHAR(50) NOT NULL,
  `correo_usuario` VARCHAR(45) NULL DEFAULT NULL,
  `telefono_usuario` INT(8) NULL DEFAULT NULL,
  `contrasena` BLOB NULL DEFAULT NULL,
  `per_id` INT NOT NULL,
  `per_reg_id` VARCHAR(3) NOT NULL,
  PRIMARY KEY (`id_usuario`, `per_id`, `per_reg_id`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC),
  INDEX `fk_usuario_personal_reg1_idx` (`per_id` ASC, `per_reg_id` ASC),
  CONSTRAINT `fk_usuario_personal_reg1`
    FOREIGN KEY (`per_id` , `per_reg_id`)
    REFERENCES `elearningdb`.`personal_reg` (`id_per` , `id_reg`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seguridad`.`bitacora_app`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`bitacora_app` (
  `id_aplicacion` INT(11) NOT NULL,
  `desc_app` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_aplicacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seguridad`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`bitacora` (
  `id_bitacora` INT(11) NOT NULL AUTO_INCREMENT,
  `id_usuario` INT(11) NOT NULL,
  `fecha_bitacora` DATE NOT NULL,
  `hora_bitacora` TIME(6) NOT NULL,
  `accion_usuario` VARCHAR(45) NOT NULL,
  `id_aplicacion` INT(11) NOT NULL,
  `resultado_bitacora` VARCHAR(45) NOT NULL,
  `error_bitacora` VARCHAR(120) NOT NULL,
  `ip_pc` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_bitacora`),
  INDEX `FK_bitacora_usuario_idx` (`id_usuario` ASC),
  INDEX `Fk_app_idx` (`id_aplicacion` ASC),
  CONSTRAINT `FK_bitacora_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `elearningdb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Fk_app`
    FOREIGN KEY (`id_aplicacion`)
    REFERENCES `elearningdb`.`bitacora_app` (`id_aplicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seguridad`.`detalle_aplicacion_derecho`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`detalle_aplicacion_derecho` (
  `id_usuario` INT(11) NOT NULL,
  `id_aplicacion` INT(11) NOT NULL,
  `ingresar` TINYINT(1) NOT NULL,
  `modificar` TINYINT(1) NOT NULL,
  `eliminar` TINYINT(1) NOT NULL,
  `imprimir` TINYINT(1) NOT NULL,
  `consultar` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_aplicacion`),
  INDEX `FK_detalle_usuario_idx` (`id_usuario` ASC),
  INDEX `FK_detalle_aplicacion2` (`id_aplicacion` ASC),
  CONSTRAINT `FK_detalle_aplicacion2`
    FOREIGN KEY (`id_aplicacion`)
    REFERENCES `elearningdb`.`aplicacion` (`id_aplicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalle_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `elearningdb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seguridad`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`perfil` (
  `id_perfil` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre_perfil` VARCHAR(50) NOT NULL,
  `descripcion_perfil` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`id_perfil`),
  UNIQUE INDEX `nombre_perfil_UNIQUE` (`nombre_perfil` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seguridad`.`detalle_perfil_aplicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`detalle_perfil_aplicacion` (
  `id_perfil` INT(11) NOT NULL,
  `id_aplicacion` INT(11) NOT NULL,
  PRIMARY KEY (`id_perfil`, `id_aplicacion`),
  INDEX `FK_detalle_aplicacion_idx` (`id_aplicacion` ASC),
  CONSTRAINT `FK_detalle_aplicacion`
    FOREIGN KEY (`id_aplicacion`)
    REFERENCES `elearningdb`.`aplicacion` (`id_aplicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalle_perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `elearningdb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seguridad`.`detalle_usuario_perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`detalle_usuario_perfil` (
  `id_usuario` INT(11) NOT NULL,
  `id_perfil` INT(11) NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_perfil`),
  INDEX `FK_detalle_up_perfil_idx` (`id_perfil` ASC),
  CONSTRAINT `FK_detalle_up_perfil`
    FOREIGN KEY (`id_perfil`)
    REFERENCES `elearningdb`.`perfil` (`id_perfil`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_detalle_up_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `selearningdb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seguridad`.`reporteador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`reporteador` (
  `idReporte` INT(11) NOT NULL,
  `nombreReporte` VARCHAR(500) NULL DEFAULT NULL,
  `path` VARCHAR(500) NULL DEFAULT NULL,
  `vista` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`idReporte`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `seguridad`.`reportegeneral`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`reportegeneral` (
  `idReporteg` INT(11) NOT NULL AUTO_INCREMENT,
  `nombreReporteg` VARCHAR(65) NOT NULL,
  `pathr` VARCHAR(128) NOT NULL,
  `reporte_app_id` INT(11) NOT NULL,
  PRIMARY KEY (`idReporteg`),
  INDEX `fk_app_id_idx` (`reporte_app_id` ASC),
  CONSTRAINT `fk_app_id`
    FOREIGN KEY (`reporte_app_id`)
    REFERENCES `elearningdb`.`aplicacion` (`id_aplicacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `elearningdb` ;

-- -----------------------------------------------------
-- Placeholder table for view `seguridad`.`vista_bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `elearningdb`.`vista_bitacora` (`usuario` INT, `fecha_bitacora` INT, `hora_bitacora` INT, `accion_usuario` INT, `desc_app` INT, `resultado_bitacora` INT, `error_bitacora` INT, `ip_pc` INT);

-- -----------------------------------------------------
-- View `seguridad`.`vista_bitacora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `elearningdb`.`vista_bitacora`;
USE `elearningdb`;
CREATE  OR REPLACE ALGORITHM=UNDEFINED DEFINER=`root`@`localhost` SQL SECURITY DEFINER VIEW `elearningdb`.`vista_bitacora` AS select `u`.`usuario` AS `usuario`,`b`.`fecha_bitacora` AS `fecha_bitacora`,`b`.`hora_bitacora` AS `hora_bitacora`,`b`.`accion_usuario` AS `accion_usuario`,`ap`.`desc_app` AS `desc_app`,`b`.`resultado_bitacora` AS `resultado_bitacora`,`b`.`error_bitacora` AS `error_bitacora`,`b`.`ip_pc` AS `ip_pc` from ((`elearningdb`.`usuario` `u` join `elearningdb`.`bitacora` `b` on((`b`.`id_usuario` = `u`.`id_usuario`))) join `elearningdb`.`bitacora_app` `ap` on((`b`.`id_aplicacion` = `ap`.`id_aplicacion`)));

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
